In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
import pickle

with open('combine_df.pickle', 'rb') as f:
    combine_df = pickle.load(f)

In [3]:
for col in ['tweet_stemmed', 'tweet_lemmatized']:
    combine_df[col] = combine_df[col].apply(lambda text_list: ' '.join(text_list))

combine_df.head(n=2)

,id,label,tweet,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,when father is dysfunctional and is so selfish...,"[when, father, is, dysfunctional, and, is, so,...","[father, dysfunctional, selfish, drags, kids, ...",father dysfunct selfish drag kid dysfunct run,father dysfunctional selfish drag kid dysfunct...
1,2,0.0,thanks for lyft credit cannot use cause they d...,"[thanks, for, lyft, credit, can, not, use, cau...","[thanks, lyft, credit, use, cause, offer, whee...",thank lyft credit use caus offer wheelchair va...,thank lyft credit use cause offer wheelchair v...

1). Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
 - Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
 - Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
 - Исключим стоп-слова с помощью stop_words='english'.
 - Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(stop_words='english',
                                   max_df=0.9,
                                   max_features=1000)

In [5]:
bow_stemmed = count_vectorizer.fit_transform(combine_df['tweet_stemmed'])
fnames_stemmed = count_vectorizer.get_feature_names()

bow_stemmed_df = pd.DataFrame(bow_stemmed.toarray(), columns=fnames_stemmed)
bow_stemmed_df.head(n=5)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
bow_lemmatized = count_vectorizer.fit_transform(combine_df['tweet_lemmatized'])
fnames_lemmatized = count_vectorizer.get_feature_names()

bow_lemmatized_df = pd.DataFrame(bow_lemmatized.toarray(), columns=fnames_lemmatized)
bow_lemmatized_df.head(n=5)

,able,absolutely,accept,account,act,action,actor,actually,adapt,add,...,yesterday,yo,yoga,york,young,youth,youtube,yr,yrs,yummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
pd.DataFrame({'stemmed': fnames_stemmed, 'lemmatized': fnames_lemmatized}).head(n=10)

   stemmed  lemmatized
0      abl        able
1  absolut  absolutely
2   accept      accept
3  account     account
4      act         act
5   action      action
6    actor       actor
7   actual    actually
8       ad       adapt
9    adapt         add

2). Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
 - Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
 - Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
 - Исключим стоп-слова с помощью stop_words='english'.
 - Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(stop_words='english',
                                   max_df=0.9,
                                   max_features=1000)

In [9]:
bow_stemmed = tfidf_vectorizer.fit_transform(combine_df['tweet_stemmed'])
fnames_stemmed = tfidf_vectorizer.get_feature_names()

bow_stemmed_df = pd.DataFrame(bow_stemmed.toarray(), columns=fnames_stemmed)
bow_stemmed_df.head(n=5)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
bow_lemmatized = tfidf_vectorizer.fit_transform(combine_df['tweet_lemmatized'])
fnames_lemmatized = tfidf_vectorizer.get_feature_names()

bow_lemmatized_df = pd.DataFrame(bow_lemmatized.toarray(), columns=fnames_lemmatized)
bow_lemmatized_df.head(n=5)

,able,absolutely,accept,account,act,action,actor,actually,adapt,add,...,yesterday,yo,yoga,york,young,youth,youtube,yr,yrs,yummy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

3). Натренируем gensim.models.Word2Vec модель на наших данных.
 - Тренировать будем на токенизированных твитах combine_df['tweet_token']
 - Установим следующие параметры: size=200, window=5, min_count=2, sg = 1, hs = 0, negative = 10, workers= 32, seed = 34.
 - Используем функцию train() с параметром total_examples равным длине combine_df['tweet_token'], количество epochs установим 20.

In [11]:
from gensim.models import Word2Vec

In [12]:
sentences = combine_df['tweet_token'].tolist()
params = {'size': 200, 'window': 5, 'min_count': 2, 'sg': 1, 'hs': 0, 'negative': 10, 'workers': 32, 'seed': 34}

In [13]:
%%time
model_w2v = Word2Vec(**params)
model_w2v.build_vocab(sentences)
model_w2v.train(sentences,
                total_examples=len(sentences),
                epochs=20)

Wall time: 2min 1s

(9154856, 11746720)

4). Давайте немного потестируем нашу модель Word2Vec и посмотрим, как она работает. Мы зададим слово positive = "dinner", и модель вытащит из корпуса наиболее похожие слова c помощью функции most_similar. То же самое попробуем со словом "trump".

In [14]:
model_w2v.most_similar(positive='dinner', topn=5)

[('cookout', 0.6032092571258545),
 ('bolognese', 0.5952011346817017),
 ('spaghetti', 0.5924275517463684),
 ('bihdaydinner', 0.5920993089675903),
 ('shawarma', 0.590448260307312)]

In [15]:
model_w2v.most_similar(positive='trump', topn=5)

[('donald', 0.5768311023712158),
 ('donaldtrump', 0.5515130758285522),
 ('suppoer', 0.5465251207351685),
 ('unfavorability', 0.5339714288711548),
 ('paladino', 0.5328047275543213)]

5). Из приведенных выше примеров мы видим, что наша модель word2vec хорошо справляется с поиском наиболее похожих слов для данного слова. Но как она это делает? Она изучила векторы для каждого уникального слова наших данных и использует косинусное сходство, чтобы найти наиболее похожие векторы (слова).
<br>Давайте проверим векторное представление любого слова из нашего корпуса, например "food".

In [16]:
print(model_w2v['food'])

[-6.52306378e-01 -8.25639889e-02  5.38134217e-01  2.14368686e-01
 -2.63084143e-01  5.08721769e-01 -9.59235549e-01  3.49557161e-01
  9.14260820e-02 -1.08841367e-01 -1.94446202e-02 -2.98645645e-01
  4.52141702e-01 -7.66237497e-01 -1.52155745e-03 -3.16472441e-01
  6.48888350e-01  7.25126922e-01 -9.21088755e-01 -2.22903285e-02
  4.96864289e-01  3.04585397e-01  4.91429307e-02 -1.37095511e-01
 -1.18090838e-01 -1.42972544e-01  1.28616646e-01 -2.58095503e-01
  3.18946719e-01  1.60454661e-01  6.33682311e-01  3.54928404e-01
 -1.28079653e-01 -3.94636869e-01  2.78255701e-01 -1.68895900e-01
 -5.75078130e-01 -4.76545602e-01  3.12864751e-01  5.24598539e-01
 -5.89911938e-01  5.25630951e-01 -3.25573757e-02 -2.47539088e-01
  5.11265919e-02  6.44236922e-01 -3.23123962e-01 -7.80316651e-01
  4.73999828e-01  8.44109356e-01  5.88878915e-02 -4.59833205e-01
  1.64621815e-01  7.14150310e-01  4.93091136e-01  5.13924837e-01
  9.66921747e-01 -2.80295610e-01 -2.34460399e-01  4.73395109e-01
  4.77611780e-01 -1.83009028e-01 -5.22627532e-01 -1.44441973e-03
  5.92117846e-01  3.63551617e-01 -2.88317148e-02 -8.43354315e-02
  2.50333428e-01  9.96220946e-01  2.86237001e-01 -3.95515174e-01
 -2.66808957e-01 -2.16453463e-01  1.08493030e-01 -2.20778808e-01
  4.38461751e-01 -2.86553204e-01 -2.06382200e-02 -1.23576798e-01
  4.35902059e-01  4.27241504e-01 -1.04782961e-01 -1.86675172e-02
 -1.62173748e-01 -8.45156968e-01  7.22296596e-01  9.19731498e-01
  2.27734253e-01  9.19870809e-02 -2.02668577e-01 -6.12834767e-02
  7.48625398e-01 -6.46112680e-01  1.55952036e-01 -1.02406874e-01
 -6.34865239e-02 -7.19316363e-01  1.03767045e-01 -3.42492342e-01
  3.11577588e-01  1.85707379e-02 -3.61895412e-01 -5.27538732e-02
  2.59922296e-01 -1.76543698e-01 -4.02547985e-01 -3.56916487e-01
  1.57847151e-01  4.71874774e-01 -3.69416088e-01  4.88822758e-02
 -1.64307013e-01 -4.94253874e-01 -2.15529621e-01 -4.20194238e-01
  4.64953333e-01 -3.01290482e-01 -2.39020586e-01 -4.05180871e-01
  6.63150549e-01 -3.93239468e-01 -1.31527758e+00 -2.26174444e-01
  2.78233945e-01 -4.12660569e-01  2.44993359e-01  2.89064888e-02
  9.87367257e-02  3.36894572e-01 -6.32966030e-03 -3.08827162e-01
  4.27385867e-01 -4.66369659e-01 -6.55786246e-02 -1.03582911e-01
  3.03105861e-01  2.57606804e-01  5.79453170e-01 -1.88319981e-01
 -1.09287649e-01  2.68664390e-01  5.89590073e-01  4.85342443e-01
 -3.15094888e-02 -5.16669393e-01  1.42880470e-01 -3.00657034e-01
  2.48150989e-01  3.02317236e-02 -7.09688962e-01 -1.81459725e-01
 -1.25213996e-01  1.68573156e-01  6.05345190e-01  4.54824716e-01
  2.25961089e-01 -5.01275882e-02 -6.00339353e-01 -6.90942287e-01
 -6.69859126e-02 -1.44612992e+00  2.61131167e-01  1.78241298e-01
  8.52946267e-02  1.28873333e-01  1.29498571e-01  4.98205721e-02
 -9.39172730e-02  6.67482615e-02  2.41769835e-01 -5.97272813e-02
 -6.91181183e-01 -8.80424500e-01  3.88738960e-01 -2.73805082e-01
 -2.68051147e-01  1.22016644e+00  8.27964172e-02 -2.12338567e-02
 -3.16321790e-01  5.50161302e-01  3.07907999e-01 -4.55376357e-01
  1.23907119e-01  9.81221721e-02  4.96943057e-01 -2.56388992e-01
  1.22440524e-01 -1.15908965e-01 -3.11480522e-01  2.79716820e-01
  5.23664176e-01  1.77925602e-01  3.27016026e-01 -2.57116646e-01
 -1.90620080e-01 -4.57205065e-02 -9.52219889e-02  3.82531613e-01]

In [17]:
model_w2v['food'].size

200

6). Поскольку наши данные содержат твиты, а не только слова, нам придется придумать способ использовать векторы слов из модели word2vec для создания векторного представления всего твита. Существует простое решение этой проблемы, мы можем просто взять среднее значение всех векторов слов, присутствующих в твите. Длина результирующего вектора будет одинаковой, то есть 200. Мы повторим тот же процесс для всех твитов в наших данных и получим их векторы. Теперь у нас есть 200 функций word2vec для наших данных.
<br>Необходимо создать вектор для каждого твита, взяв среднее значение векторов слов, присутствующих в твите. В цикле сделать: <br>vec += model_w2v[word].reshape((1, size))
<br>и поделить финальный вектор на количество слов в твите.
<br>На выходе должен получиться wordvec_df.shape = (49159, 200).

In [18]:
def text2vec(text_list, size=200):
    n_words = len(text_list)
    vec = np.zeros((1, size))
    if n_words == 0:
        return vec
    for word in text_list:
        try:
            vec += model_w2v[word].reshape((1, size))
        except KeyError:
            # KeyError: "word 'Z' not in vocabulary"
            # как вариант - установить min_count = 1
            continue
    return vec / n_words

In [19]:
wordvec_df = combine_df['tweet_token'].apply(text2vec)

In [20]:
wordvec_df = np.concatenate(wordvec_df)
wordvec_df.shape

(49159, 200)